/**
 * BBF Archive Server — ohashiayaka.com offline mirror
 */
import { createServer, type IncomingMessage, type ServerResponse } from 'node:http';
import { existsSync, statSync, createReadStream, readFileSync } from 'node:fs';
import { join, extname } from 'node:path';
import { config } from './config/index.js';
import { lookup } from './mime.js';

const { publicDir, port } = config;

/**
 * Load pre-parsed calendar events (generated by embed_calendar.mjs).
 * Used to serve FullCalendar AJAX requests offline.
 */
const CALENDAR_JSON_PATH = join(publicDir, 'calendar-events.json');
let calendarEvents: Buffer | null = null;
try {
  if (existsSync(CALENDAR_JSON_PATH)) {
    calendarEvents = readFileSync(CALENDAR_JSON_PATH);
    console.log(`  Calendar: ${JSON.parse(calendarEvents.toString()).length} events loaded`);
  }
} catch { /* calendar events not built yet */ }

/** Resolve a URL path to a file on disk, or null */
function resolvePath(urlPath: string): string | null {
  if (urlPath === '/') {
    const fp = join(publicDir, 'index.html');
    return existsSync(fp) ? fp : null;
  }
  const clean = urlPath.endsWith('/') ? urlPath.slice(0, -1) : urlPath;
  const exact = join(publicDir, clean);
  try { if (statSync(exact).isFile()) return exact; } catch {}
  if (!extname(clean)) {
    const html = join(publicDir, `${clean}.html`);
    if (existsSync(html)) return html;
  }
  if (!extname(clean)) {
    const idx = join(publicDir, clean, 'index.html');
    if (existsSync(idx)) return idx;
  }
  return null;
}

/** Detect AJAX/JSON request (FullCalendar-style) */
function isAjaxRequest(req: IncomingMessage): boolean {
  const accept = req.headers['accept'] || '';
  const xrw = req.headers['x-requested-with'] || '';
  return accept.includes('application/json') || xrw === 'XMLHttpRequest';
}

/** Main request handler */
function handleRequest(req: IncomingMessage, res: ServerResponse): void {
  if (req.method !== 'GET' && req.method !== 'HEAD') {
    res.writeHead(405); res.end(); return;
  }

  const url = req.url || '/';
  const [urlPath, queryString] = url.split('?');

  // ── Handle ?page=N pagination → serve _page_N.html ──
  if (queryString) {
    const pageMatch = queryString.match(/^page=(\d+)$/);
    if (pageMatch) {
      const pagedPath = `${urlPath}_page_${pageMatch[1]}`;
      const pagedFile = resolvePath(pagedPath);
      if (pagedFile) {
        res.writeHead(200, {
          'Content-Type': lookup(extname(pagedFile).toLowerCase()),
          'Cache-Control': 'public, max-age=3600',
        });
        createReadStream(pagedFile).pipe(res);
        return;
      }
    }
  }

  // ── Calendar AJAX → return JSON events ──
  if ((urlPath === '/calendar' || urlPath === '/contents_calendar') && isAjaxRequest(req) && calendarEvents) {
    res.writeHead(200, {
      'Content-Type': 'application/json; charset=utf-8',
      'Cache-Control': 'public, max-age=3600',
    });
    res.end(calendarEvents);
    return;
  }

  // ── Normal file serving ──
  const filePath = resolvePath(urlPath);
  if (filePath) {
    const ext = extname(filePath).toLowerCase();
    const stat = statSync(filePath);
    const fileSize = stat.size;
    const range = req.headers.range;

    if (range) {
      // Parse Range: "bytes=start-end"
      const parts = range.replace(/bytes=/, '').split('-');
      const start = parseInt(parts[0], 10);
      const end = parts[1] ? parseInt(parts[1], 10) : fileSize - 1;
      const chunkSize = end - start + 1;

      res.writeHead(206, {
        'Content-Range': `bytes ${start}-${end}/${fileSize}`,
        'Accept-Ranges': 'bytes',
        'Content-Length': chunkSize,
        'Content-Type': lookup(ext),
        'Cache-Control': 'public, max-age=3600',
      });
      createReadStream(filePath, { start, end }).pipe(res);
    } else {
      res.writeHead(200, {
        'Content-Type': lookup(ext),
        'Content-Length': fileSize,
        'Accept-Ranges': 'bytes',
        'Cache-Control': 'public, max-age=3600',
      });
      createReadStream(filePath).pipe(res);
    }
  } else {
    // 404 → homepage
    const index = join(publicDir, 'index.html');
    res.writeHead(404, { 'Content-Type': 'text/html; charset=utf-8' });
    createReadStream(index).pipe(res);
  }
}

const server = createServer(handleRequest);
server.listen(port, () => {
  console.log(`\n  BBF Archive Server`);
  console.log(`  http://localhost:${port}\n`);
});
